### ISSUE TITLE
Working on an update for Teams

### ISSUE THREAD

**Issue by DEberhardt** [UpStartTech/Skype#2]
Hello Jeff,

Thank you for this wonderful Script for Skype Online Functions - They are very useful!
I see the last update is a few years in the past, so I started working to make it usable for Teams.
A few License changes I have scoped out (added M365 licenses, removed E1s, etc.)
New to github, so don't know how to share...

**Comment by JeffBrownTech** [comment]
Hi there, thanks for the comment, glad you have found the project useful.

I'm actually going to start working on a new version myself, I've split this into a separate repo and will be adding more to it. But here's my suggestion. I'm fine with you creating your own repo underneath your account and uploading your version there and keep it as your own from now on.

Or if you want, you can fork my repo and use it as a starting point for your own repo and upload your new version there.

https://help.github.com/en/github/getting-started-with-github/fork-a-repo

No need to upload your own here as I most likely won't be maintaining this version moving forward.
